version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: payment_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    command: sh -c "sleep 10 && /app/payment_system"

volumes:
  postgres_data: